#!/usr/bin/ruby
# Copyright (c) 2010 Mark Somerville <mark@scottishclimbs.com>
# Released under the GNU General Public License (GPL) version 3.
# See COPYING.

require "optparse"
require "#{File.dirname(__FILE__)}/lib/shell"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: urchin [options]"

  opts.on("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on("-c", "--commands [COMMANDS]", "Run this command string, then exit") do |command_string|
    options[:command_string] = command_string
  end
end.parse!

# If we are not the controlling process, we won't be able to set the foreground
# process group unless we ignore or block SIGTTOU.
Signal.trap :TTOU, "IGNORE"

Dir.glob("builtins/*.rb").each do |path|
  require path
end

if options[:command_string]
  Urchin::Shell.new.run(options[:command_string])
else
  # TODO: ensure we are the foreground job before starting to run interactively.
  @shell = Urchin::Shell.new

  module Urchin
    JOB_TABLE = JobTable.new
  end

  Signal.trap :TSTP, "IGNORE"

  @shell.run_interactively
end
